dradis/dradis-projects

- dradis-projects.gemspec
- lib/tasks/thorfile.rb
Currently, the `dradis:plugins:projects:export:package` thor command fails with a stack trace. 
This example command:
`$ PROJECT_ID=96 RAILS_ENV=production bundle exec thor dradis:plugins:projects:export:package`
Fails with the following stack trace: 
```
D, [2017-04-05T21:12:03.883127 #4689] DEBUG -- : Creating a new Zip file in /opt/dradispro/dradispro/releases/20160721072805/backup/dradis-export_2017-04-05_2.zip...
D, [2017-04-05T21:12:03.891617 #4689] DEBUG -- : 	Adding XML repository dump
/opt/dradispro/dradispro/releases/20160721072805/vendor/cache/dradis-plugins-3a24c50550ac/lib/dradis/plugins/content_service/boards.rb:6:in `all_boards': undefined method `id' for nil:NilClass (NoMethodError)
from /opt/dradispro/dradispro/releases/20160721072805/lib/dradis/pro/plugins/projects/export …
```
> Add project_id to opts

- dradis-projects.gemspec
- lib/tasks/thorfile.rb
The `dradis:plugins:projects:upload:package` command currently fails with a stack trace. 
The following sample command: 
`$ PROJECT_ID=96 RAILS_ENV=production bundle exec thor dradis:plugins:projects:upload:package /tmp/dradis-export.zip`
fails with the following stack trace:
```
/opt/dradispro/dradispro/releases/20160721072805/vendor/cache/dradis-projects-1c29dd12967d/lib/tasks/thorfile.rb:137:in `package': undefined method `new' for Dradis::Plugins::ContentService:Module (NoMethodError)
from /opt/dradispro/dradispro/shared/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
from /opt/dradispro/dradispro/shared/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
from /opt/dradispro/dradispro/shared/bundle/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb …
```
> Fix upload task

- lib/dradis/plugins/projects/upload/v1/template.rb
While creating a project from an old project template, I found and 'invalid template' error.
Looks like if the project has no report content data (a CONTENTLIB Node), we are not catching it properly.
With this PR, if no info related to the CONTENTLIB Node is found in the xml template, nothing should happen.
> find a type element inside a node with value 4, then take its parent

- CHANGELOG.md
- lib/dradis/plugins/projects/export/v1/template.rb
- lib/dradis/plugins/projects/gem_version.rb
- Export a CE project that contains methodologies
-  Check the exported xml, assert that `<methodology>` tags have a `version` attribute with value  `1`
> Export fix: add version attribute to xml exported methodologies  

- lib/dradis/plugins/projects/upload/v1/template.rb
I've noticed that we were already keeping some nodes unique on import using their label (the `plugin-output` node).
This PR pretends to keep system nodes unique, detecting them by their type_id
(everything that is not in `Node::Types::DEFAULT` or `Node::Types::HOST` is a system node)
> keep system nodes unique

- lib/dradis/plugins/projects/upload/v1/template.rb
Fixes: http://discuss.dradisframework.org/t/error-while-importing-owasp-project/492
With the new parent validation for nodes, the parsing of nodes in the template upload breaks because it relies on the fact that you can save nodes with invalid parent ID. This solution skips the validation when saving child nodes and only validate them properly when they have the right parent id.
In CE,
1. Download the OWASP package https://dradisframework.com/academy/industry/compliance/owasp/
2. Upload the file .zip file in the package
3. Assert that there were no errors in uploading.
> Fix nodes upload

- lib/dradis/plugins/projects/upload/v1/template.rb
Currently, the importer assigns `-1` as a user id for activities when the user email is missing.
Use the default_user_id instead.
1. Create a temporary user.
2. Login to the user and create a project.
3. Perform activities in the project (create/delete/update issues/evidences/nodes)
4. Export the project as a template.
5. Login to a different user (admin).
6. Delete the temporary user.
7. Create a project template using the exported template in #4.
8. Create a project using the project template.
9. Assert that the project was created.
> Add default user id as fallback for activity user when importing.

- lib/dradis/plugins/projects/engine.rb
- lib/dradis/plugins/projects/export/template.rb
- lib/dradis/plugins/projects/export/v1/template.rb
- lib/dradis/plugins/projects/export/v2/template.rb
- lib/dradis/plugins/projects/upload/template.rb
- lib/dradis/plugins/projects/upload/v1/template.rb
- lib/dradis/plugins/projects/upload/v2/template.rb
- lib/tasks/thorfile.rb
We want to have the ability to export/import comments in Projects to be able to migrate the discussion along with the findings.
Add builders and parsers in dradis-projects for Comments
*Note: this PR is more easily tested once there's a way to view comments*
1. Create a project
2. Add an issue
3. Add comments to the issue
4. Export the project
5. Create a new project(2)
6. Upload the export from Step 4 to project(2).
7. Assert that the comments were migrated.
> Comments export import

- lib/dradis/plugins/projects/upload/v1/template.rb
When uploading a project in Pro, an error appears:
```
[14:00:41] Validation failed: Project must exist
```
This is because the Node is not created in the context of the project. The same applies for activities.
> Fix project upload

- CHANGELOG.md
- lib/dradis/plugins/projects/export/v1/template.rb
- lib/dradis/plugins/projects/upload/v1/template.rb
- spec/fixtures/files/with_comments.xml
- spec/lib/dradis/plugins/projects/export/v2/template_spec.rb
- spec/lib/dradis/plugins/projects/upload/v2/template_spec.rb
Reviewer notes: update the base branch when #35 is merged.
Since we're adding comments to evidence, we also need to have a way to export and import them.
When exporting, we need to build the comments when building the evidence in the file `Dradis::Plugins::Projects::Export::V1::Template`.
When importing, we parse the comments when importing the evidence in the file `Dradis::Plugins::Projects::Upload::V1::Template`.
1. In a project add an evidence
2. Add comments to the evidence
3. Export the project and assert that the comments were added to the XML.
4. Import the exported project to an empty project
5. Assert that the comments were created.
> Evidence comments

- lib/dradis/plugins/projects/engine.rb
- lib/dradis/plugins/projects/upload/template.rb
- lib/dradis/plugins/projects/upload/v3/template.rb
When importing as a package or template, we should be accepting the new `<board>` format in the imported xml, or the old `<methodologies>` format
Test using Test using: https://github.com/dradis/dradis-plugins/pull/31
- Import an old template and package files, with methodologies still not using boards
- After import we should have a methodology ready to be migrated into a board /check project summary page)
- Import an new template and package files, with methodologies using boards
- After import we should have a boards when we click on `Methodologies` in the sidebar
> Port Boards: Import

- CHANGELOG.md
- lib/dradis/plugins/projects/engine.rb
- lib/dradis/plugins/projects/export/template.rb
- lib/dradis/plugins/projects/export/v3/template.rb
- lib/dradis/plugins/projects/gem_version.rb
- lib/dradis/plugins/projects/upload/template.rb
- lib/dradis/plugins/projects/upload/v3/template.rb
Spec
When importing as a package or template, we should be accepting the new <board> format in the imported xml, or the old <methodologies> format
How to test
Importing
- Import an old template and package files, with methodologies still not using boards
- After import we should have a methodology ready to be migrated into a board /check project summary page)
- Import an new template and package files, with methodologies using boards
- After import we should have a boards when we click on Methodologies in the sidebar
Exporting
- Create a board with lists and a tasks
- Export the project as a template and as package using the web
- Assert that in the exported xml files (also the one inside the zip), we see the exported boards as
- <methodologies><board …
> Port boards IO

- lib/dradis/plugins/projects/gem_version.rb
We will not be version bumping the non-tagged master changes until we release v1.15.0.
As per new version bumping guidelines. Master may contain code that is between versions.
> Remove rc versioning

- .gitignore
- CHANGELOG.md
- lib/dradis/plugins/projects/export/v2/template.rb
- lib/dradis/plugins/projects/gem_version.rb
- lib/dradis/plugins/projects/upload/v2/template.rb
- spec/fixtures/files/with_comments.xml
- spec/lib/dradis/plugins/projects/export/v2/template_spec.rb
- spec/lib/dradis/plugins/projects/upload/v2/template_spec.rb
Currently, an export error is thrown when exporting a project with a comment by a deleted user.
Error: 
```
bundler: failed to load command: thor (/opt/dradispro/dradispro/releases/202008020007/vendor/bundle/ruby/2.4.0/bin/thor)
NoMethodError: undefined method `email' for nil:NilClass
/opt/dradispro/dradispro/shared/bundle/ruby/2.4.0/gems/dradis-projects-3.18.0/lib/dradis/plugins/projects/export/v2/template.rb:14:in `block (3 levels) in build_comments_for'
```
Handle nil users when exporting comments. The exported author attribute for those comments will now be blank.
Setup the project:
1. As an admin, create a project and an issue in the project.
2. Create a temporary user. Assign this user to the project
3. Login as the temporary user and comment on the issue
4. …
> Fix deleted author for comments

- lib/dradis/plugins/projects/export/v3/template.rb
Instead of having Template know how to build the Board XML representation, push that down to the Board class itself.
See: https://github.com/dradis/dradis-ce/pull/797
> Export::Template - push the Board conversion XML to the model

- CHANGELOG.md
- lib/dradis/plugins/projects/upload/v1/template.rb
- lib/dradis/plugins/projects/upload/v3/template.rb
Since the last release when a project package or template is imported it is no longer nesting nodes appropriately. It orphans all nodes to the root level.
Use integers in places integers should not be strings. This is achieved in two ways. Cast with an error using `Integer()` where we always expect an int. In the event a nil value is also valid (previous_id) use `to_i`
> Fix node parent

- CHANGELOG.md
- lib/dradis/plugins/projects/upload/v1/template.rb
- spec/fixtures/files/missing_node.xml
- spec/lib/dradis/plugins/projects/upload/v1/template_spec.rb
When uploading a project export with a reference to an attachment that is from a deleted node, the following error is thrown:
```
> [09:39:34] Setting issue_id for evidence
> [09:39:34] can't convert nil into Integer
> [09:39:34] Worker process completed.
```
The error is thrown from ruby String's % method. In the line:
```
"!%s/projects/%d/nodes/%d/attachments/%s!" % [$1, project.id, lookup_table[:nodes][$2.to_i], $3]
```
nodes/%d expects a number coming from the lookup_table. But if the node isn't present in the table, it returns `nil` and the can't convert nil into Integer error is thrown. A simple example would be:
```
'%d' % nil
```
throwing the same error.
Catch the case when the node_id from the attachment is not found in the lookup table.
> Catch missing nodes for attachments

- CHANGELOG.md
- lib/dradis/plugins/projects/engine.rb
- lib/dradis/plugins/projects/upload/package.rb
- lib/dradis/plugins/projects/upload/template.rb
Provide no-op plugin mappings. We just need to ensure the plugin registers both template, and package options.
> Provide upload mapping options

- dradis-projects.gemspec
- lib/dradis/plugins/projects/engine.rb
- lib/dradis/plugins/projects/export/template.rb
- lib/dradis/plugins/projects/export/v1/template.rb
- lib/dradis/plugins/projects/export/v2/template.rb
- lib/dradis/plugins/projects/export/v3/template.rb
- lib/dradis/plugins/projects/export/v4/template.rb
- lib/dradis/plugins/projects/upload/template.rb
- lib/dradis/plugins/projects/upload/v1/template.rb
- lib/dradis/plugins/projects/upload/v2/template.rb
- lib/dradis/plugins/projects/upload/v3/template.rb
- lib/dradis/plugins/projects/upload/v4/template.rb
- spec/fixtures/files/with_invalid_states.xml
- spec/fixtures/files/with_states.xml
- spec/lib/dradis/plugins/projects/export/v2/template_spec.rb
- spec/lib/dradis/plugins/projects/export/v4/template_spec.rb
- spec/lib/dradis/plugins/projects/upload/v1/template_spec.rb
- spec/lib/dradis/plugins/projects/upload/v2/template_spec.rb
- spec/lib/dradis/plugins/projects/upload/v4/template_spec.rb
With the introduction of the state column for issues/content blocks, we want to make sure that the state can be exported and imported along with the project.
Implement an import/export V4 that adds the state attribute.
> QA import/export projects

- CHANGELOG.md
- lib/dradis/plugins/projects/gem_version.rb
- lib/dradis/plugins/projects/upload/v4/template.rb
- spec/fixtures/files/attachments_url.xml
- spec/fixtures/files/with_tags.xml
- spec/lib/dradis/plugins/projects/upload/v4/template_spec.rb
With the introduction of custom tag sorting, we want to maintain the user-set order of tags when uploading an exported project template
> I assign all rights, including copyright, to any future Dradis
> work by myself to Security Roots.
> Update tag position when uploading template
